config/routes.rb
require 'action_dispatch/routing/mapper'

Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { session: 'users/sessions' }

 # devise_for :users
  # Example:
  resources :blog_posts

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
require 'blog_post' # Add the missing import statement

class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :set_blog_post, except: [:index, :new, :create]

  
  def index
    if user_signed_in?
    @blog_posts = BlogPost.all
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @blog_post = BlogPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
  end

  def new
    if user_signed_in?
    @blog_post = BlogPost.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    if user_signed_in?
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end

    else
      redirect_to new_user_session_path
    end
  end

  def edit
    if user_signed_in?
    @blog_post = BlogPost.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def update 
    if user_signed_in?
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end

    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    if
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body)
  end
  def set_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model:@blog_post, local: true) do |form| %>
  <% if @blog_post.errors.any? %>
    <div>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger">
          <p><%= msg %></p>
        </div>
      <% end %>
    </div>
  <% end %>

  <!-- Your form fields go here -->
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br>
  <%= form.label :body %>
  <%= form.text_area :body %>
  <br>
 <%= form.submit(@blog_post.new_record? ? "Create Blog Post" : "Update Blog Post") %>
<% end %>

app/views/blog_posts/edit.html.erb
<h2>Edit</h2>

<form>
  <%= render partial: "form", locals: { blog_post: @blog_post } %>
   <%= link_to "Home", blog_posts_path %> | <%= link_to "Back", blog_post_path(@blog_post) %> |

  <%= button_to "Delete", @blog_post, method: :delete, data: { confirm: 'Are you sure?' } %>
</form>

app/views/blog_posts/index.html.erb
<h1>BlogPosts#index</h1>

<p>Find me in app/views/blog_posts/index.html.erb</p>

<% @blog_posts.each do |blog_posts| %>
<div> <span> Create a <%= link_to "New", new_blog_post_path(blog_posts) %> Blog </span> </div>
<div class="blog_post">
  <h2><%= link_to blog_posts.title, blog_post_path(blog_posts) %></h2>
  <p><%= blog_posts.body %></p>
 
 <p><%= link_to "Edit", edit_blog_post_path(blog_posts) %> </p> 
</div>


<% end %>
```

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render partial: "form", locals: { blog_post: @blog_posts} %>

app/views/blog_posts/show.html.erb
<%# Add the missing import statements %>
<%# Import the necessary Rails helper methods %>
<%# Add the missing import statements %>
<h1> Show Blog Post </h1>
<% @blog_post = BlogPost.find(params[:id]) %>
  

<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.body %></p>

<p><%= link_to "Back", :back %> | <%= link_to "Edit", edit_blog_post_path(@blog_post) %> | <%= link_to "New", new_blog_post_path(@blog_post) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GorailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<div>
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</div>
    <%= yield %>
  </body>
</html>